# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodexQuota < Formula
  desc "Terminal account switcher and quota monitor for Codex/OpenCode"
  homepage "https://github.com/nam98nd16/codex-quota"
  version "0.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.8/codex-quota_0.3.8_darwin_amd64.tar.gz"
      sha256 "44dedb3f627ac774396c6a3f1dbc8db0104acbe13c0f05ea0cd341854314a3ff"

      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.8/codex-quota_0.3.8_darwin_arm64.tar.gz"
      sha256 "3aa2f3f5b28454e198ff0659523678fd0186b5025bd835f928c6d65970ce094b"

      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.8/codex-quota_0.3.8_linux_amd64.tar.gz"
      sha256 "810e7e713b981eb252bd0db7c0afcefb96519fa44da05c102064e5ed1dca37e0"
      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.8/codex-quota_0.3.8_linux_arm64.tar.gz"
      sha256 "91906d85fff79c64103db28a93209e23b33c15c819532ca7a30556b2e0b2080c"
      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  test do
    system "#{bin}/cq", "--help"
  end
end
