# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodexQuota < Formula
  desc "Terminal account switcher and quota monitor for Codex/OpenCode"
  homepage "https://github.com/nam98nd16/codex-quota"
  version "0.3.43"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.43/codex-quota_0.3.43_darwin_amd64.tar.gz"
      sha256 "355065ffa7cac1d251e1649aec310b9026006cd912ad7e60807b4f6d61d63739"

      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.43/codex-quota_0.3.43_darwin_arm64.tar.gz"
      sha256 "941c2ecfa3ef863100059ec2e88b010982582facb714d09051133e5e3dab1251"

      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.43/codex-quota_0.3.43_linux_amd64.tar.gz"
      sha256 "f06a1d3de5327ac7f556456ebeb0d7700bae924389f5c1829b24d966f27ed626"
      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.43/codex-quota_0.3.43_linux_arm64.tar.gz"
      sha256 "436b59adcdea9052986d87a71b12c6ccb8ee79fd3bd14139e2f2bf8a95196cb8"
      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  test do
    system "#{bin}/cq", "--help"
  end
end
