# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodexQuota < Formula
  desc "Terminal account switcher and quota monitor for Codex/OpenCode"
  homepage "https://github.com/nam98nd16/codex-quota"
  version "0.3.49"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.49/codex-quota_0.3.49_darwin_amd64.tar.gz"
      sha256 "89303a040f80ec24ba0bee0b7d58fc57e92b0b313047b246ff427edc5a277f41"

      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.49/codex-quota_0.3.49_darwin_arm64.tar.gz"
      sha256 "ee2ab18540f2ab6b01135af09b881b9e6db864f2bf33ccf9854899393a58b873"

      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.49/codex-quota_0.3.49_linux_amd64.tar.gz"
      sha256 "c91adf32a975de05cd337b1e6519ae44a9483a5db5e133535372b26b35e8c474"
      define_method(:install) do
        bin.install "cq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nam98nd16/codex-quota/releases/download/v0.3.49/codex-quota_0.3.49_linux_arm64.tar.gz"
      sha256 "8dd5c4798c9bb87861b020789d111fa4f529a37f4ba86319ba01050d6eac402a"
      define_method(:install) do
        bin.install "cq"
      end
    end
  end

  test do
    system "#{bin}/cq", "--help"
  end
end
